### ISSUE TITLE
using dot-product for aggregation

### ISSUE THREAD

**Issue by jsadler2** [ks905383/xagg_archived#10]
Hi @ks905383 - first of all, want to say that I think what you have done with `xagg` is very exciting! I echo what Ryan Abernathy said in #6 that this would serve a lot of use cases. 

I had been coming at this problem in a separate but very similar way starting several months ago. One difference in the approach I was taking is that I used a dot-product to do the `aggregate` step. To do this, my version of `weightmap.agg` is a xarray DataArray instead of a pandas DataFrame. I can then do a `.dot` with each array in my xarray DataSet. 

I switched out the current method in `aggregate` with using a dot product and  found using the dot product approach to be _much_ more efficient. I ran a test on a dataset with 10 variables and a time dimension of 14625 aggregated to 53 polygons (see attached for html outputs of the notebooks):
approach | time to perform aggregation (minutes)
-|-
currently implemented | 20.9
dot product | 0.5

I'm no computing expert, but I think the big difference is that the dot product turns the problem into a matrix multiplication which is very efficient. I used 10 Dask workers in both test cases and I think that the dot product approach also utilizes those workers much more effectively. 

This could be a pretty big change to your code, but is this something you'd be interesting in trying out? If so, I can start a PR we can start discussing how to make the change. [My current branch](https://github.com/ks905383/xagg/compare/main...jsadler2:dot-product) is functional, but I don't think it conforms to all the functionality you currently have (e.g., having the option of custom weights). I'd be very happy to work on this PR. 

Again, I really like what you have so far. I find the way you've calculated the weight matrix and your api very intuitive and much better than what I was writing up as a one-off. Having the (much) more efficient aggregation step using the dot product would be great and I think would be of interest to other `xagg` users.

[xagg_dot_product_test.zip](https://github.com/ks905383/xagg/files/6320993/xagg_dot_product_test.zip)

**Comment by ks905383** [comment]
Hi @jsadler2 -

This looks quite interesting, thank you for the work you've already done on this! From a first quick glance at it, I really like this approach - first of all, it seems like it's a lot cleaner, and also I can't argue with that benchmarking. 

I'm not accepting PRs _juuuuuust_ yet - I want the full set of unit tests I'm working on to be complete and stable before any new major changes are made (mainly, this is happening in a fresh repo for a few reasons; so I'll be migrating all of this over soon). *However* - I really hope I can get that done in the next few days, and after that I'd more than welcome contributions. 

So - in short, yes, please feel free to keep working on this, and I'll be more than happy to help as well once I get the rest of this backend off my plate (again, hopefully in the next few days).

**Comment by jsadler2** [comment]
That sounds great. Makes sense to have unit tests in place before accepting PRs.

**Comment by ks905383** [comment]
Hi @jsadler2 - 

I finally managed to squeeze in the work to get the testing workflow setup. Everything's been moved over to https://github.com/ks905383/xagg to deal with a lot of crap in the git history and get a fresh start. If you're still interested in getting this incorporated, I'd love to see how it fits in / help integrate it into `xagg`!

**Comment by jsadler2** [comment]
Sounds good. Yeah. I'm still interested. I will make an issue in the new repo.
