### ISSUE TITLE
set up CI, testing, etc.

### ISSUE THREAD

**Issue by rabernat** [ks905383/xagg_archived#6]
I'm excited about this package! Looks like it solves a general problem that many people are interested in. 👏 

If you want to take the next steps in terms of making your package ready for public distribution (including welcoming contributions from other developers), it will probably need:
- comprehensive unit and integration tests
- narrative and API documentation
- code linting
- continuous integration of the above via github workflows

Fortunately @jbusecke (also of LDEO!) put together a fantastic "cookie cutter" package template which includes all of this and more: https://github.com/jbusecke/cookiecutter-science-project

I'm sure Julius would be happy to spend some time explaining how you might adapt this for xarray.

Thanks again for sharing!

**Comment by ks905383** [comment]
Thank you for the advice / links! These are definitely my next goals with this.

**Comment by jbusecke** [comment]
Hi @ks905383, I also think this is a very promising package, that the community needs. I can think of a few projects of mine where this would be helpful.

I would love to help where I can. I see two ways to approach this: 

You can set up a 'brand new' repository with the cookie-cutter template, migrate your code over to that and take care of the renaming at some point (that is a bit finicky I believe, let's talk about it before anything is renamed). But overall I think this can save you a lot of time.

I am also working on a documentation part for the cookie-cutter, that explains how to set up all the components step by step (https://github.com/jbusecke/cookiecutter-science-project/blob/master/build_components_from_scratch.md). This is however still incomplete, and not advertised. Id be willing to put some time into that as a parallel exercise to help with this project, if you are interested in building each component up from scratch. But I think that would take significantly longer. 

@rabernat do you have thoughts on renaming, replacing an entire repo on github and potential pitfalls to avoid?

**Comment by rabernat** [comment]
> @rabernat do you have thoughts on renaming, replacing an entire repo on github and potential pitfalls to avoid?

My impression is that, while the core code is very valuable, this repo itself is quite messy. Many files have been committed that don't belong in version control (eggs, ipynb_checkpoints, builds, dist, pycache, .DS_store, etc.). Even if you `git rm` them, the git history will carry these around forever with the repo.

So I would recommend starting with a clean template repo and copy just the python code files over.

**Comment by jbusecke** [comment]
Ok thats what my first intuition was too. So maybe a good way to proceed is to rename this repo to `xagg_archived` and create a clean `xagg` using the template. Then you can migrate the python files into the new repo and start with the unit tests ? 
 Once the migration is complete, the `xagg_archived` can be deleted I guess.

**Comment by rabernat** [comment]
Sounds reasonable, but it's really all up to Kevin how to proceed.

**Comment by jbusecke** [comment]
Oh yeah for sure. I did not mean to give the impression of highjacking this project at all. This was mainly something I did not know myself and was just curious about other opinions.

**Comment by ks905383** [comment]
Months later, I finally got around to this. 

Check out the new stable repo (with a functional testing workflow) at https://github.com/ks905383/xagg

and the docs at https://xagg.readthedocs.io/en/latest/

Thanks again for the helps/tips!

**Comment by jbusecke** [comment]
👏 Awesome!
