### ISSUE TITLE
No module named `xesmf`

### ISSUE THREAD

**Issue by jrising** [ks905383/xagg_archived#7]
I'm running into package conflicts trying to setup `xagg`. Although the "No module" error is an `xagg` problem, I'm not sure the package conflicts are. But I think what is needed is a working install procedure for `xagg`.

I'm starting from a fresh python 3.7 conda environment, and successfully install xarray, geopandas, and xagg.

But `import xagg` results in `ModuleNotFoundError: No module named 'xesmf'`. No worries, I go to install `xesmf` (which prefers conda, which is why I'm trying it this way). But conda runs into package conflicts, which stem at least from `esmpy`

I am able to get things working, by specifying `esmpy=7.1.0` and then installing `xesmf` (one of which somehow changes the default python in my environment to python 3.8, breaking everything if I don't specify python 3.7). But I'm sure if I had to do it again, I would spend many hours again.

**Comment by ks905383** [comment]
Argh; `xesmf` and its dependents are the bane of my existence for package conflicts... 

I'll look into this. I thought that the newest versions of `xesmf` fixed that package conflict issue with `esmpy`, but maybe I haven't updated the dependencies in `xagg` to reflect that.

Thanks for pointing this out!

**Comment by ks905383** [comment]
Dependencies have been updated in the latest version - could you see if you still run into this issue? Also I've moved over all the code into a fresh repo to deal with some structural issues - all future dev will happen over at https://github.com/ks905383/xagg .

**Comment by jrising** [comment]
Yes, that worked! Thanks for digging into this.
