### ISSUE TITLE
Implausible aggregated results

### ISSUE THREAD

**Issue by jrising** [ks905383/xagg_archived#9]
I'm aggregating SSTs and getting values that are outside of the range of the data. I suspect that this is because masked-out regions (land) are being replaced with 0s, or something similar.

Is this something that can be handled by `xagg`? It seems like it would be quite difficult to generate a shapefile that aligns exactly to the masking of the data.

Here's a link to the data, with the code in `state-sst.py`:
https://www.dropbox.com/sh/d4iba44mrfbpc7d/AABxheu2_TXyNKEPIlZU4PXka?dl=0

**Comment by ks905383** [comment]
Ah yes - I see it - a lot of -40 deg C SSTs. 

Let me take a look.

**Comment by ks905383** [comment]
Ok - yeah, I've found a way to fix the issue. It was indeed an issue with masked-out pixels still being counted in the weighted average, but only contributing 0 each. 

I have it working on my own machine; I'll see if I can get a stable build out with this fix in the next few days.

**Comment by jrising** [comment]
Thanks!

**Comment by ks905383** [comment]
https://test.pypi.org/project/xagg/0.1.4/ 
New test version is installable on testpypi right now - this should fix all the code problems from issues #8 and #9

**Comment by ks905383** [comment]
Should be fixed with `0.1.4`, which is now live on pypi as well
